name: 'Delete Inactive Users in Github Organization'

on:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  org-config-generation-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions/checkout@v3
        with:
          path: community
      - name: Generate github org configuration
        id: uds
        run: |
          python -m pip install --upgrade pip
          pip install -r community/org/requirements.txt
          python community/org/org_user_management.py -gt ${{ secrets.GH_TOKEN }}
      - name: Create Pull Request
        if: ${{ steps.uds.outputs.inactive_users_pr_description }}
        uses: peter-evans/create-pull-request@v4
        with:
          path: community
          add-paths: org/contributors.yml
          commit-message: Delete inactive users
          branch: delete-inactive-users
          title: 'Inactive users to be deleted'
          body: ${{ steps.uds.outputs.inactive_users_pr_description }}
